baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "troop 4575"
[params]
  description = "Girl Scouts of Greater Los Angeles"
  author = "Nikola Tesla"
  

[[menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
    url = "/getting-started/"
    
[[menu.side]]
    name = "side about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.side]]
    name = "side getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -120
    url = "/getting-started/"